language: java
sudo: true
jdk: oraclejdk11
before_install:
- chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: L/NAGZ6CIqoYnMS8Yg3rCnumH3sSEgyQJ/g63AO3XbSC+bc+61MBgegFDVrDxLzu+xofLAYjpOBnrvx0wO3sJm6X594NIjcfAQ1B8FIvTFxGgYLtH0s/p6CDn8k6ohtP1tJqGN37nu576DduOVj8MvRLZIDUSkCdgCnjIDafSeWFUkJCJ0DznXhDYWhmrqN1w4V9JNN1My+mB13gY0p8n78pXM3FohnvL/J+9uXH6amzSghMSBaxbC247U1XD533cfExKlMMy7J4cZm3VrOzMaINn8Z5Y+zaBvvBF6HCkfYvdsJZ0crHrEeLlziRsqNXhjnsS0cQM61EZEEk/zMHTtpScjiQBADNKiN0FtEL15q+XwwQRcgLb/oNvGqygkB7Vhe5m/Nih52ZqUCCxNI7/vS6mGHfZCx2DPaZfcKFWgv2MzZCjm9zoZm0QywjwJE3Zn6Dft+KJo0NhO3ShBCUYgxVSJ7Wt2lHprGb/y5Ea4Odz5EhjGr8mNjqXzfKJsf/2ppY1MnSYgh5tfAmQIbpjjz+ZeX7uUYh0qB9cqmKcA/nesAykrZDpLgNMg8wMLR8AQGZhjN9zeqQjkg/B6QEx3I2YlLRqLWEU4gHz0E4mbAZ5WRmylZ33zLVyvCkq6qik58iKP8l+KyozGZv9SdApr0zkqFbORpIVOBZr3s3L8w=
  app: ticketing--system
  on:
    repo: TadeasMusil/ticketing-system
