language: java
sudo: true
jdk: oraclejdk11
before_install:
- chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: USjkh7Oe1pylHsK9CojlofQnby3iMwvymqwpsJI6UMBzTLH9IpmJDC/obmvmIVD/onXm0LAKx5RHL5fJEfUK1Znhll2Rb/+ox3UMQle4mvFhElicYO6N8q4PM9kz0YDevX4Uyi0ELKmG6iAecPK7jYR5QglzwnaM8azV6PqBaQffpKy7npHAxywGrDmAafQCxCWGqmljjGECCGc2mAxLnaVbonYLPINdxyAlkUztFPUvkbZXD41oPTb4nOAm8VdaLnH36LwfkBg2PHdeFA99+9yNN99DEsmm3ZB7yKiJANDEaxOMmDK5stLkIHWIjKp8eGFz8hbt673e9lf4dvxGFb1YCVP3sgPiLU2URP5vxEl5FDuWck1xh8wZ59nJd/CIWHWDRLueAuxzNAwc7ogHk2lPy1B2jlEg4GCk7VbdvJWv1tmZqQSqCoSEULvMMUGbte5XXV1kzt2nv7DtbohDIqw9M8fu535veLjHPSBs+OGdKaUfmzku5t9ZsDEMvAsjqQcFPuwdCgvSHBOezmzk/lYb1OQniMR2cgQq3DJbP9mQ9zipt00o70QvvBydI/Y1yI2UTpvxr/F4bO6+fcoXjbyqj4SS55F6oOMaUhOULiD0UKkY5KiQF7XIrAsSaJVUn4dbsqfjUuSGti9Pg/ZBXlfmwPp57FDtqvumn4qf7IU=
  app: ticketing--system
  on:
    repo: TadeasMusil/ticketing-system
